/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */

/* THIS FILE IS AUTOGENERATED! */
#ifndef __OOMKILL_BPF_SKEL_H__
#define __OOMKILL_BPF_SKEL_H__

#include <errno.h>
#include <stdlib.h>
#include <bpf/libbpf.h>

struct oomkill_bpf {
	struct bpf_object_skeleton *skeleton;
	struct bpf_object *obj;
	struct {
		struct bpf_map *tbl_oomkill;
	} maps;
	struct {
		struct bpf_program *netdata_oom_mark_victim;
	} progs;
	struct {
		struct bpf_link *netdata_oom_mark_victim;
	} links;
};

static void
oomkill_bpf__destroy(struct oomkill_bpf *obj)
{
	if (!obj)
		return;
	if (obj->skeleton)
		bpf_object__destroy_skeleton(obj->skeleton);
	free(obj);
}

static inline int
oomkill_bpf__create_skeleton(struct oomkill_bpf *obj);

static inline struct oomkill_bpf *
oomkill_bpf__open_opts(const struct bpf_object_open_opts *opts)
{
	struct oomkill_bpf *obj;
	int err;

	obj = (struct oomkill_bpf *)calloc(1, sizeof(*obj));
	if (!obj) {
		errno = ENOMEM;
		return NULL;
	}

	err = oomkill_bpf__create_skeleton(obj);
	if (err)
		goto err_out;

	err = bpf_object__open_skeleton(obj->skeleton, opts);
	if (err)
		goto err_out;

	return obj;
err_out:
	oomkill_bpf__destroy(obj);
	errno = -err;
	return NULL;
}

static inline struct oomkill_bpf *
oomkill_bpf__open(void)
{
	return oomkill_bpf__open_opts(NULL);
}

static inline int
oomkill_bpf__load(struct oomkill_bpf *obj)
{
	return bpf_object__load_skeleton(obj->skeleton);
}

static inline struct oomkill_bpf *
oomkill_bpf__open_and_load(void)
{
	struct oomkill_bpf *obj;
	int err;

	obj = oomkill_bpf__open();
	if (!obj)
		return NULL;
	err = oomkill_bpf__load(obj);
	if (err) {
		oomkill_bpf__destroy(obj);
		errno = -err;
		return NULL;
	}
	return obj;
}

static inline int
oomkill_bpf__attach(struct oomkill_bpf *obj)
{
	return bpf_object__attach_skeleton(obj->skeleton);
}

static inline void
oomkill_bpf__detach(struct oomkill_bpf *obj)
{
	return bpf_object__detach_skeleton(obj->skeleton);
}

static inline const void *oomkill_bpf__elf_bytes(size_t *sz);

static inline int
oomkill_bpf__create_skeleton(struct oomkill_bpf *obj)
{
	struct bpf_object_skeleton *s;

	s = (struct bpf_object_skeleton *)calloc(1, sizeof(*s));
	if (!s)
		goto err;
	obj->skeleton = s;

	s->sz = sizeof(*s);
	s->name = "oomkill_bpf";
	s->obj = &obj->obj;

	/* maps */
	s->map_cnt = 1;
	s->map_skel_sz = sizeof(*s->maps);
	s->maps = (struct bpf_map_skeleton *)calloc(s->map_cnt, s->map_skel_sz);
	if (!s->maps)
		goto err;

	s->maps[0].name = "tbl_oomkill";
	s->maps[0].map = &obj->maps.tbl_oomkill;

	/* programs */
	s->prog_cnt = 1;
	s->prog_skel_sz = sizeof(*s->progs);
	s->progs = (struct bpf_prog_skeleton *)calloc(s->prog_cnt, s->prog_skel_sz);
	if (!s->progs)
		goto err;

	s->progs[0].name = "netdata_oom_mark_victim";
	s->progs[0].prog = &obj->progs.netdata_oom_mark_victim;
	s->progs[0].link = &obj->links.netdata_oom_mark_victim;

	s->data = (void *)oomkill_bpf__elf_bytes(&s->data_sz);

	return 0;
err:
	bpf_object__destroy_skeleton(s);
	return -ENOMEM;
}

static inline const void *oomkill_bpf__elf_bytes(size_t *sz)
{
	*sz = 2520;
	return (const void *)"\
\x7f\x45\x4c\x46\x02\x01\x01\0\0\0\0\0\0\0\0\0\x01\0\xf7\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x98\x06\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\x40\0\x0d\0\
\x0c\0\x61\x11\x08\0\0\0\0\0\x63\x1a\xfc\xff\0\0\0\0\xb7\x01\0\0\0\0\0\0\x73\
\x1a\xfb\xff\0\0\0\0\xbf\xa2\0\0\0\0\0\0\x07\x02\0\0\xfc\xff\xff\xff\xbf\xa3\0\
\0\0\0\0\0\x07\x03\0\0\xfb\xff\xff\xff\x18\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xb7\
\x04\0\0\0\0\0\0\x85\0\0\0\x02\0\0\0\xb7\0\0\0\0\0\0\0\x95\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x47\x50\x4c\0\x9f\
\xeb\x01\0\x18\0\0\0\0\0\0\0\xc8\x01\0\0\xc8\x01\0\0\x99\x01\0\0\0\0\0\0\0\0\0\
\x02\x03\0\0\0\x01\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\x01\0\0\0\0\0\0\0\x03\0\0\
\0\0\x02\0\0\0\x04\0\0\0\x05\0\0\0\x05\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\0\0\0\
\0\0\0\0\0\x02\x02\0\0\0\0\0\0\0\0\0\0\x02\x07\0\0\0\x19\0\0\0\0\0\0\x08\x08\0\
\0\0\x1e\0\0\0\0\0\0\x01\x01\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\x02\x0a\0\0\0\0\0\0\
\0\0\0\0\x03\0\0\0\0\x02\0\0\0\x04\0\0\0\x40\0\0\0\0\0\0\0\x04\0\0\x04\x20\0\0\
\0\x2c\0\0\0\x01\0\0\0\0\0\0\0\x31\0\0\0\x05\0\0\0\x40\0\0\0\x35\0\0\0\x06\0\0\
\0\x80\0\0\0\x3b\0\0\0\x09\0\0\0\xc0\0\0\0\x47\0\0\0\0\0\0\x0e\x0b\0\0\0\x01\0\
\0\0\0\0\0\0\0\0\0\x02\x0e\0\0\0\x53\0\0\0\x02\0\0\x04\x10\0\0\0\x71\0\0\0\x0f\
\0\0\0\0\0\0\0\x75\0\0\0\x02\0\0\0\x40\0\0\0\x79\0\0\0\0\0\0\x08\x10\0\0\0\x7d\
\0\0\0\0\0\0\x08\x11\0\0\0\x83\0\0\0\0\0\0\x01\x08\0\0\0\x40\0\0\0\0\0\0\0\x01\
\0\0\x0d\x02\0\0\0\x9a\0\0\0\x0d\0\0\0\x9e\0\0\0\x01\0\0\x0c\x12\0\0\0\x7d\x01\
\0\0\0\0\0\x01\x01\0\0\0\x08\0\0\x01\0\0\0\0\0\0\0\x03\0\0\0\0\x14\0\0\0\x04\0\
\0\0\x04\0\0\0\x82\x01\0\0\0\0\0\x0e\x15\0\0\0\x01\0\0\0\x8b\x01\0\0\x01\0\0\
\x0f\0\0\0\0\x0c\0\0\0\0\0\0\0\x20\0\0\0\x91\x01\0\0\x01\0\0\x0f\0\0\0\0\x16\0\
\0\0\0\0\0\0\x04\0\0\0\0\x69\x6e\x74\0\x5f\x5f\x41\x52\x52\x41\x59\x5f\x53\x49\
\x5a\x45\x5f\x54\x59\x50\x45\x5f\x5f\0\x5f\x5f\x75\x38\0\x75\x6e\x73\x69\x67\
\x6e\x65\x64\x20\x63\x68\x61\x72\0\x74\x79\x70\x65\0\x6b\x65\x79\0\x76\x61\x6c\
\x75\x65\0\x6d\x61\x78\x5f\x65\x6e\x74\x72\x69\x65\x73\0\x74\x62\x6c\x5f\x6f\
\x6f\x6d\x6b\x69\x6c\x6c\0\x6e\x65\x74\x64\x61\x74\x61\x5f\x6f\x6f\x6d\x5f\x6d\
\x61\x72\x6b\x5f\x76\x69\x63\x74\x69\x6d\x5f\x65\x6e\x74\x72\x79\0\x70\x61\x64\
\0\x70\x69\x64\0\x75\x36\x34\0\x5f\x5f\x75\x36\x34\0\x6c\x6f\x6e\x67\x20\x6c\
\x6f\x6e\x67\x20\x75\x6e\x73\x69\x67\x6e\x65\x64\x20\x69\x6e\x74\0\x70\x74\x72\
\0\x6e\x65\x74\x64\x61\x74\x61\x5f\x6f\x6f\x6d\x5f\x6d\x61\x72\x6b\x5f\x76\x69\
\x63\x74\x69\x6d\0\x74\x72\x61\x63\x65\x70\x6f\x69\x6e\x74\x2f\x6f\x6f\x6d\x2f\
\x6d\x61\x72\x6b\x5f\x76\x69\x63\x74\x69\x6d\0\x2f\x68\x6f\x6d\x65\x2f\x74\x68\
\x69\x61\x67\x6f\x2f\x4e\x65\x74\x64\x61\x74\x61\x2f\x6b\x65\x72\x6e\x65\x6c\
\x2d\x63\x6f\x6c\x6c\x65\x63\x74\x6f\x72\x2f\x63\x6f\x2d\x72\x65\x2f\x6f\x6f\
\x6d\x6b\x69\x6c\x6c\x2e\x62\x70\x66\x2e\x63\0\x20\x20\x20\x20\x69\x6e\x74\x20\
\x6b\x65\x79\x20\x3d\x20\x70\x74\x72\x2d\x3e\x70\x69\x64\x3b\0\x20\x20\x20\x20\
\x75\x38\x20\x76\x61\x6c\x20\x3d\x20\x30\x3b\0\x20\x20\x20\x20\x62\x70\x66\x5f\
\x6d\x61\x70\x5f\x75\x70\x64\x61\x74\x65\x5f\x65\x6c\x65\x6d\x28\x26\x74\x62\
\x6c\x5f\x6f\x6f\x6d\x6b\x69\x6c\x6c\x2c\x20\x26\x6b\x65\x79\x2c\x20\x26\x76\
\x61\x6c\x2c\x20\x42\x50\x46\x5f\x41\x4e\x59\x29\x3b\0\x20\x20\x20\x20\x72\x65\
\x74\x75\x72\x6e\x20\x30\x3b\0\x63\x68\x61\x72\0\x5f\x6c\x69\x63\x65\x6e\x73\
\x65\0\x2e\x6d\x61\x70\x73\0\x6c\x69\x63\x65\x6e\x73\x65\0\x9f\xeb\x01\0\x20\0\
\0\0\0\0\0\0\x14\0\0\0\x14\0\0\0\x6c\0\0\0\x80\0\0\0\0\0\0\0\x08\0\0\0\xb6\0\0\
\0\x01\0\0\0\0\0\0\0\x13\0\0\0\x10\0\0\0\xb6\0\0\0\x06\0\0\0\0\0\0\0\xd1\0\0\0\
\x0b\x01\0\0\x14\x74\0\0\x08\0\0\0\xd1\0\0\0\x0b\x01\0\0\x09\x74\0\0\x18\0\0\0\
\xd1\0\0\0\x23\x01\0\0\x08\x78\0\0\x28\0\0\0\xd1\0\0\0\0\0\0\0\0\0\0\0\x40\0\0\
\0\xd1\0\0\0\x33\x01\0\0\x05\x7c\0\0\x60\0\0\0\xd1\0\0\0\x6f\x01\0\0\x05\x80\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x02\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1a\0\0\0\x12\0\x02\0\0\0\0\0\0\0\0\0\x70\0\0\0\
\0\0\0\0\x51\0\0\0\x11\0\x03\0\0\0\0\0\0\0\0\0\x20\0\0\0\0\0\0\0\x6b\0\0\0\x11\
\0\x04\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\x01\0\0\0\x03\0\0\
\0\xc0\x01\0\0\0\0\0\0\x04\0\0\0\x03\0\0\0\xd8\x01\0\0\0\0\0\0\x04\0\0\0\x04\0\
\0\0\x2c\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x40\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\
\0\x50\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x60\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\
\x70\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x80\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\
\x90\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x08\x09\x0a\0\x2e\x74\x65\x78\x74\0\x2e\
\x72\x65\x6c\x2e\x42\x54\x46\x2e\x65\x78\x74\0\x2e\x6d\x61\x70\x73\0\x6e\x65\
\x74\x64\x61\x74\x61\x5f\x6f\x6f\x6d\x5f\x6d\x61\x72\x6b\x5f\x76\x69\x63\x74\
\x69\x6d\0\x2e\x72\x65\x6c\x74\x72\x61\x63\x65\x70\x6f\x69\x6e\x74\x2f\x6f\x6f\
\x6d\x2f\x6d\x61\x72\x6b\x5f\x76\x69\x63\x74\x69\x6d\0\x74\x62\x6c\x5f\x6f\x6f\
\x6d\x6b\x69\x6c\x6c\0\x2e\x6c\x6c\x76\x6d\x5f\x61\x64\x64\x72\x73\x69\x67\0\
\x5f\x6c\x69\x63\x65\x6e\x73\x65\0\x2e\x73\x74\x72\x74\x61\x62\0\x2e\x73\x79\
\x6d\x74\x61\x62\0\x2e\x72\x65\x6c\x2e\x42\x54\x46\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\x36\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\
\x70\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x14\0\0\0\
\x01\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xb0\0\0\0\0\0\0\0\x20\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x6c\0\0\0\x01\0\0\0\x03\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xd0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x88\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\xd4\0\0\0\0\0\0\0\x79\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x0b\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x4d\
\x04\0\0\0\0\0\0\xa0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\x7c\0\0\0\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xf0\x04\0\0\0\0\0\0\
\x78\0\0\0\0\0\0\0\x0c\0\0\0\x02\0\0\0\x08\0\0\0\0\0\0\0\x18\0\0\0\0\0\0\0\x32\
\0\0\0\x09\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x68\x05\0\0\0\0\0\0\x10\0\0\0\
\0\0\0\0\x07\0\0\0\x02\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x84\0\0\0\x09\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x78\x05\0\0\0\0\0\0\x20\0\0\0\0\0\0\0\
\x07\0\0\0\x05\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x07\0\0\0\x09\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x98\x05\0\0\0\0\0\0\x70\0\0\0\0\0\0\0\x07\0\0\0\
\x06\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x5d\0\0\0\x03\x4c\xff\x6f\0\0\0\
\x80\0\0\0\0\0\0\0\0\0\0\0\0\x08\x06\0\0\0\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x74\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\x0b\x06\0\0\0\0\0\0\x8d\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0";
}

#endif /* __OOMKILL_BPF_SKEL_H__ */
