FROM ubuntu:26.04 AS build

ARG ARCH=x86
ENV ARCH=$ARCH

ARG LOCAL_KERNEL_VERSION=6.18.31
ENV LOCAL_KERNEL_VERSION=$LOCAL_KERNEL_VERSION

ENV _LIBC=glibc

ENV DEBIAN_FRONTEND=noninteractive
# hadolint ignore=DL3018,DL3015,DL3008,DL3009
RUN apt-get update && \
    apt-get install -y build-essential autoconf automake coreutils pkg-config \
                       bc libelf-dev libssl-dev clang-22 clang-tools-22 libclang-22-dev \
                       llvm-22 rsync bison flex tar xz-utils wget libbfd-dev \
                       golang-go \
                       libcap-dev

# hadolint ignore=DL3059
RUN ln -sf /usr/bin/clang-22 /usr/bin/clang && \
    ln -sf /usr/bin/llvm-strip-22 /usr/bin/llvm-strip

# hadolint ignore=DL3003,SC3009,DL4006,SC2046
RUN mkdir -p /usr/src && \
    cd /usr/src && \
    wget -q https://cdn.kernel.org/pub/linux/kernel/v$(echo "$LOCAL_KERNEL_VERSION" | cut -f 1 -d '.').x/linux-${LOCAL_KERNEL_VERSION}.tar.xz && \
    tar -xf linux-${LOCAL_KERNEL_VERSION}.tar.xz && \
    make -C linux-${LOCAL_KERNEL_VERSION}/tools/bpf/bpftool/ && \
    cp linux-${LOCAL_KERNEL_VERSION}/tools/bpf/bpftool/bpftool /usr/bin/

WORKDIR /ebpf-co-re

COPY .dockerfiles/build_core.sh /build.sh
COPY . .

CMD ["/build.sh"]
