#ifndef NETDATA_BPF_ARENA_COMPAT_H
#define NETDATA_BPF_ARENA_COMPAT_H

#ifndef BPF_MAP_TYPE_ARENA
#ifdef BPF_MAP_TYPE_CGRP_STORAGE
#define BPF_MAP_TYPE_ARENA (BPF_MAP_TYPE_CGRP_STORAGE + 1)
#else
#define BPF_MAP_TYPE_ARENA 33
#endif
#endif

#endif /* NETDATA_BPF_ARENA_COMPAT_H */
