#ifndef NETDATA_BPF_ARENA_COMPAT_H
#define NETDATA_BPF_ARENA_COMPAT_H

#undef __BPF_FEATURE_ADDR_SPACE_CAST

#ifndef BPF_MAP_TYPE_ARENA
#define BPF_MAP_TYPE_ARENA 35
#endif

#endif /* NETDATA_BPF_ARENA_COMPAT_H */
